const ru = {
  common: { loading: 'Загрузка...', error: 'Ошибка', close: 'Закрыть', save: 'Сохранить', cancel: 'Отмена', delete: 'Удалить', add: 'Добавить', edit: 'Изменить', logout: 'Выйти', back: '← На главную', demo: 'Демо: demo@books.com / demo123' },
  nav: { library: 'Библиотека', wishlist: 'Вишлист', genres: 'Жанры', stats: 'Статистика', profile: 'Профиль', login: 'Войти', register: 'Регистрация' },
  landing: { title: 'Ваша личная библиотека', subtitle: 'Ведите коллекцию прочитанных книг, планируйте чтение и отслеживайте прогресс в одном месте.', cta: 'Начать бесплатно', ctaLogin: 'Войти', ctaOpen: 'Открыть библиотеку →', feature1Title: 'Каталог книг', feature1Desc: 'Добавляйте книги, отмечайте статус: читаю, прочитано, хочу прочитать.', feature2Title: 'Рейтинги', feature2Desc: 'Оценивайте прочитанные книги и всегда помните что понравилось.', feature3Title: 'Статистика', feature3Desc: 'Наглядная аналитика: сколько книг прочитано, любимые жанры.', feature4Title: 'Жанры', feature4Desc: 'Организуйте коллекцию по жанрам и находите похожие книги.' },
  auth: { loginTitle: 'Добро пожаловать', loginSubtitle: 'Войдите в свой аккаунт', registerTitle: 'Создать аккаунт', registerSubtitle: 'Начните собирать свою библиотеку', email: 'Email', password: 'Пароль', name: 'Имя', loginBtn: 'Войти', registerBtn: 'Зарегистрироваться', noAccount: 'Нет аккаунта?', hasAccount: 'Уже есть аккаунт?', newPassword: 'Новый пароль (оставьте пустым, чтобы не менять)', passwordHint: 'Минимум 6 символов', registrationDate: 'Дата регистрации', saved: '✓ Сохранено!' },
  books: { title: '📚 Моя библиотека', addBook: '+ Добавить книгу', searchPlaceholder: '🔍 Название или автор...', empty: 'Библиотека пуста. Добавьте первую книгу!', emptyFilter: 'Ничего не найдено по фильтрам.', statusAll: 'Все', statusReading: '▶ Читаю', statusRead: '✓ Прочитано', filterGenre: 'Все жанры', markRead: '✓ Прочитано', markReading: '▶ Читаю', confirmDelete: 'Удалить книгу из библиотеки?', statusRead2: 'Прочитано', statusReading2: 'Читаю', statusWishlist: 'Хочу прочитать' },
  wishlist: { title: '🔖 Список желаний', empty: 'Список пуст. Добавляйте книги со статусом «Хочу прочитать»!', confirmDelete: 'Удалить из вишлиста?', count: 'книг в очереди на прочтение' },
  genres: { title: '🏷️ Жанры', addTitle: '+ Добавить жанр', namePlaceholder: 'Например: Графический роман', descPlaceholder: 'Краткое описание жанра', colorLabel: 'Цвет', bookCount: 'кн.' },
  stats: { title: '📊 Статистика чтения', read: 'Прочитано', reading: 'Читаю сейчас', wishlist: 'В вишлисте', pages: 'Страниц прочитано', avgRating: 'Средняя оценка', total: 'Всего книг', topGenres: '🏷️ Жанры', topRated: '⭐ Топ оценок' },
  profile: { title: '👤 Личный кабинет', settings: 'Настройки', read: 'Прочитано', reading: 'Читаю', total: 'Всего', pages: 'Страниц прочитано', logoutBtn: 'Выйти из аккаунта' },
  notFound: { title: 'Страница не найдена', subtitle: 'Похоже, эта страница пропала, как закладка из книги. Вернитесь на главную.' }
} as const;

export default ru;
